/**
 * Core types for Agentic Context Engineering (ACE) framework
 */

/**
 * Represents a task to be processed by the ACE framework
 */
export interface Task {
  id: string;
  query: string;
  context?: Record<string, any>;
}

/**
 * A reasoning trajectory generated by the Generator
 */
export interface Trajectory {
  id: string;
  taskId: string;
  query: string;
  reasoning: string;
  answer: string;
  success: boolean;
  timestamp: Date;
}

/**
 * An insight extracted by the Reflector
 */
export interface Insight {
  id: string;
  content: string;
  type: 'helpful' | 'harmful';
  category: string;
  examples: string[];
  confidence: number;
  timestamp: Date;
}

/**
 * A delta update proposed by the Curator
 */
export interface DeltaUpdate {
  id: string;
  insightId: string;
  operation: 'add' | 'update' | 'merge' | 'prune';
  targetSection: string;
  content: string;
  metadata: {
    helpfulCount: number;
    harmfulCount: number;
    lastUpdated: Date;
  };
}

/**
 * A section in the playbook
 */
export interface PlaybookSection {
  id: string;
  name: string;
  strategies: Strategy[];
  metadata: {
    created: Date;
    lastUpdated: Date;
    usageCount: number;
  };
}

/**
 * A strategy in the playbook
 */
export interface Strategy {
  id: string;
  content: string;
  type: 'helpful' | 'harmful';
  helpfulCount: number;
  harmfulCount: number;
  examples: string[];
  confidence: number;
  created: Date;
  lastUpdated: Date;
}

/**
 * The evolving playbook that accumulates knowledge
 */
export interface Playbook {
  id: string;
  sections: Map<string, PlaybookSection>;
  globalStrategies: Strategy[];
  metadata: {
    version: number;
    created: Date;
    lastUpdated: Date;
    totalUpdates: number;
  };
}

/**
 * Configuration for the ACE framework
 */
export interface ACEConfig {
  modelName: string;
  apiKey: string;
  maxTokens?: number;
  temperature?: number;

  // Generator config
  generatorConfig?: {
    maxTrajectories?: number;
    includePlaybook?: boolean;
  };

  // Reflector config
  reflectorConfig?: {
    minConfidence?: number;
    compareSuccessAndFailure?: boolean;
  };

  // Curator config
  curatorConfig?: {
    deduplicationThreshold?: number;
    pruningThreshold?: number;
    maxStrategiesPerSection?: number;
  };
}

/**
 * Result of ACE processing
 */
export interface ACEResult {
  task: Task;
  trajectory: Trajectory;
  insights: Insight[];
  updates: DeltaUpdate[];
  updatedPlaybook: Playbook;
}
